name: Build

on:
  push:
    branches: master
  schedule:
    - cron: "0 4 * * FRI"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
